basePath: /v1
definitions:
  TagSet:
    additionalProperties:
      type: string
    type: object
  sandboxAuthResponse:
    properties:
      apiKey:
        type: string
      operatorId:
        type: string
      token:
        type: string
      userName:
        type: string
  sandboxBeamCounts:
    properties:
      count:
        format: int64
        type: integer
  sandboxCreateCouponRequest:
    properties:
      amount:
        example: 1000
        format: int32
        type: integer
      applicableBillItemName:
        enum:
        - dailyDataTrafficChargeTotal
        - dailyChargeTotal
        - dailySoracomBeamRequestChargeTotal
        example: dailyDataTrafficChargeTotal
        type: string
      expiryYearMonth:
        example: yyyyMM
        type: string
  sandboxCreateCouponResponse:
    properties:
      amount:
        description: クーポン額
        format: double
        type: number
      balance:
        description: 残高
        format: double
        type: number
      billItemName:
        description: 対象課金アイテム
        type: string
      couponCode:
        description: クーポンコード
        type: string
      expiryYearMonth:
        description: 有効期限
        example: yyyyMM
        type: string
  sandboxCreateSubscriberRequest:
    properties:
      subscription:
        type: string
  sandboxCreateSubscriberResponse:
    properties:
      apn:
        type: string
      createdAt:
        format: int64
        type: integer
      expiryTime:
        format: int64
        type: integer
      imsi:
        type: string
      ipAddress:
        type: string
      lastModifiedAt:
        format: int64
        type: integer
      msisdn:
        type: string
      operatorId:
        type: string
      registrationSecret:
        type: string
      serialNumber:
        type: string
      speedClass:
        type: string
      status:
        type: string
      subscription:
        type: string
      tags:
        $ref: '#/definitions/TagSet'
  sandboxDataTrafficStats:
    properties:
      downloadByteSizeTotal:
        format: int64
        type: integer
      downloadPacketSizeTotal:
        format: int64
        type: integer
      uploadByteSizeTotal:
        format: int64
        type: integer
      uploadPacketSizeTotal:
        format: int64
        type: integer
  sandboxGetSignupTokenRequest:
    properties:
      authKey:
        type: string
      authKeyId:
        type: string
  sandboxGetSignupTokenResponse:
    properties:
      token:
        type: string
    required:
    - token
  sandboxInitRequest:
    properties:
      authKey:
        type: string
      authKeyId:
        type: string
      coverageTypes:
        items:
          type: string
        type: array
      email:
        type: string
      password:
        type: string
      registerPaymentMethod:
        default: true
        type: boolean
    required:
    - email
    - password
    - authKeyId
    - authKey
  sandboxInsertAirStatsRequest:
    properties:
      dataTrafficStatsMap:
        properties:
          s1.fast:
            $ref: '#/definitions/sandboxDataTrafficStats'
          s1.minimum:
            $ref: '#/definitions/sandboxDataTrafficStats'
          s1.slow:
            $ref: '#/definitions/sandboxDataTrafficStats'
          s1.standard:
            $ref: '#/definitions/sandboxDataTrafficStats'
        type: object
      unixtime:
        description: UNIX 時刻（ミリ秒単位）
        format: int64
        type: integer
  sandboxInsertBeamStatsRequest:
    properties:
      beamStatsMap:
        properties:
          inHttp:
            $ref: '#/definitions/sandboxBeamCounts'
          inMqtt:
            $ref: '#/definitions/sandboxBeamCounts'
          inTcp:
            $ref: '#/definitions/sandboxBeamCounts'
          inUdp:
            $ref: '#/definitions/sandboxBeamCounts'
          outHttp:
            $ref: '#/definitions/sandboxBeamCounts'
          outHttps:
            $ref: '#/definitions/sandboxBeamCounts'
          outMqtt:
            $ref: '#/definitions/sandboxBeamCounts'
          outMqtts:
            $ref: '#/definitions/sandboxBeamCounts'
          outTcp:
            $ref: '#/definitions/sandboxBeamCounts'
          outTcps:
            $ref: '#/definitions/sandboxBeamCounts'
          outUdp:
            $ref: '#/definitions/sandboxBeamCounts'
        type: object
      unixtime:
        description: UNIX 時刻（ミリ秒単位）
        format: int64
        type: integer
  sandboxShipOrderRequest:
    properties:
      operatorId:
        type: string
      orderId:
        type: string
    required:
    - orderId
    - operatorId
host: api-sandbox.soracom.io
info:
  description: SORACOM SANDBOX API v1
  title: SORACOM SANDBOX API
  version: "20160218"
paths:
  /sandbox/coupons/create:
    post:
      consumes:
      - application/json
      description: クーポンをを新規作成します。
      operationId: sandboxCreateCoupon
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sandboxCreateCouponRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sandboxCreateCouponResponse'
        "400":
          description: API の引数が誤っている。
      security:
      - api_key: []
      - api_token: []
      summary: クーポンを作成する
      tags:
      - Coupon
      x-soracom-cli:
      - sandbox coupons create
  /sandbox/init:
    post:
      consumes:
      - application/json
      description: Operator のサインアップ、認証および課金情報の登録を行います。サンドボックス環境に新しく作成するオペレーターの email
        と password、本番環境の SAM ユーザーの authKeyId と authKey をリクエストに含めてください。オペレーターの作成に成功した場合、API
        キーと API トークンが返されるので、以降の認証が必要なリクエスト時にはこの API キーと API トークンをヘッダーに付与してリクエストを行ってください。
      operationId: sandboxInitializeOperator
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sandboxInitRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Sandbox 用の Operator の作成に成功
          schema:
            $ref: '#/definitions/sandboxAuthResponse'
        "400":
          description: メールアドレスが不正もしくは AuthKeyId, AuthKey が誤っている。
      summary: Operator を初期化する
      tags:
      - Operator
      x-soracom-cli:
      - sandbox init
  /sandbox/operators/{operator_id}:
    delete:
      consumes:
      - application/json
      description: Operator を削除します。
      operationId: sandboxDeleteOperator
      parameters:
      - description: operator_id
        in: path
        name: operator_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Operator が存在しない
      security:
      - api_key: []
      - api_token: []
      summary: Operator を削除する
      tags:
      - Operator
      x-soracom-cli:
      - sandbox operators delete
  /sandbox/operators/token/{email}:
    post:
      consumes:
      - application/json
      description: 登録確認用のサインアップトークンを取得します。API の引数に本番環境の SAM ユーザーの AuthKeyId と AuthKey
        を指定してください。
      operationId: sandboxGetSignupToken
      parameters:
      - description: 認証リクエスト
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/sandboxGetSignupTokenRequest'
      - description: email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 認証成功
          schema:
            $ref: '#/definitions/sandboxGetSignupTokenResponse'
        "400":
          description: メールアドレス、AuthKeyId、AuthKey のいずれかが誤っている。
      summary: サインアップトークンを取得する
      tags:
      - Operator
      x-soracom-cli:
      - sandbox operators get-signup-token
  /sandbox/orders/ship:
    post:
      consumes:
      - application/json
      description: 指定された Order を出荷済み状態に変更し、Order に含まれる Subscriber を準備完了状態にします。
      operationId: sandboxShipOrder
      parameters:
      - description: Shipping request
        in: body
        name: shippingRequest
        required: true
        schema:
          $ref: '#/definitions/sandboxShipOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Order が存在しない
      security:
      - api_key: []
      - api_token: []
      summary: Order を出荷済状態にする
      tags:
      - Order
      x-soracom-cli:
      - sandbox orders ship
  /sandbox/stats/air/subscribers/{imsi}:
    post:
      consumes:
      - application/json
      description: Air の統計情報としてテスト用データ（上り下りのデータ通信量、タイムスタンプ付き）を投入します。Sandbox 内部で日ごと・月ごとの統計情報も自動的に累計されて取得できるようになります。同じタイムスタンプで複数回データを投入することはできません。
      operationId: sandboxInsertAirStats
      parameters:
      - description: IMSI
        in: path
        name: imsi
        required: true
        type: string
      - description: ある時点のデータ通信量の統計情報
        in: body
        name: stats
        required: true
        schema:
          $ref: '#/definitions/sandboxInsertAirStatsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 同じ IMSI に対して同じタイムスタンプのデータが投入された
      security:
      - api_key: []
      - api_token: []
      summary: テスト用に Air の統計情報を登録する
      tags:
      - Stats
      x-soracom-cli:
      - sandbox stats air insert
  /sandbox/stats/beam/subscribers/{imsi}:
    post:
      consumes:
      - application/json
      description: Beam の統計情報としてテスト用データ（リクエスト数、タイムスタンプ付き）を投入します。Sandbox 内部で日ごと・月ごとの統計情報も自動的に累計されて取得できるようになります。同じタイムスタンプで複数回データを投入することはできません。
      operationId: sandboxInsertBeamStats
      parameters:
      - description: IMSI
        in: path
        name: imsi
        required: true
        type: string
      - description: ある時点のリクエスト数の統計情報
        in: body
        name: stats
        required: true
        schema:
          $ref: '#/definitions/sandboxInsertBeamStatsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 同じ IMSI に対して同じタイムスタンプのデータが投入された
      security:
      - api_key: []
      - api_token: []
      summary: テスト用に Beam の統計情報を登録する
      tags:
      - Stats
      x-soracom-cli:
      - sandbox stats beam insert
  /sandbox/subscribers/create:
    post:
      description: Subscriber を新規作成します
      operationId: sandboxCreateSubscriber
      parameters:
      - description: Create request
        in: body
        name: createRequest
        required: false
        schema:
          $ref: '#/definitions/sandboxCreateSubscriberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sandboxCreateSubscriberResponse'
      security:
      - api_key: []
      - api_token: []
      summary: Subscriber を作成する
      tags:
      - Subscriber
      x-soracom-cli:
      - sandbox subscribers create
produces:
- application/json
schemes:
- https
securityDefinitions: {}
swagger: "2.0"
