name: Go

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports

      - name: Install go-assets-builder
        run: go get github.com/jessevdk/go-assets-builder

      - name: Generate
        run: go generate -v ./generagors/cmd/src/

      - name: Format
        run: goimports -w ./generators/

      - name: Test
        run: go test ./generators/cmd/src

      - name: Test
        run: go test ./generators/lib

      - name: Build the generator
        run: go build -o generate-cmd ./generators/cmd/src

      - name: Run the generator
        run: ./generate-cmd -a generators/assets/soracom-api.en.yaml -s generators/assets/sandbox/soracom-sandbox-api.en.yaml -t generators/cmd/templates -p generators/cmd/predefined -o soracom/generated/cmd/

      - name: Generate
        run: go generate -v ./soracom/ && ls ./soracom/ && ls ./soracom/generated/ && ls ./soracom/generated/cmd && ls ./soracom/generated/cmd/i18n_data.go

      #- name: Install a dependency which is required only for windows
      #run: go get -u github.com/bearmini/go-acl

      - name: Format
        run: goimports -w ./soracom/

      - name: Build
        run: |
          GOOS=linux   GOARCH=amd64 go build -o soracom/dist/ghactions/linux-amd64/soracom   ./soracom
          GOOS=linux   GOARCH=386   go build -o soracom/dist/ghactions/linux-386/soracom     ./soracom
          GOOS=linux   GOARCH=arm   go build -o soracom/dist/ghactions/linux-arm/soracom     ./soracom
          GOOS=darwin  GOARCH=amd64 go build -o soracom/dist/ghactions/darwin-amd64/soracom  ./soracom
          GOOS=windows GOARCH=amd64 go build -o soracom/dist/ghactions/windows-amd64/soracom ./soracom
          GOOS=windows GOARCH=386   go build -o soracom/dist/ghactions/windows-386/soracom   ./soracom
          GOOS=freebsd GOARCH=amd64 go build -o soracom/dist/ghactions/freebsd-amd64/soracom ./soracom
          GOOS=freebsd GOARCH=386   go build -o soracom/dist/ghactions/freebsd-386/soracom   ./soracom

      - uses: actions/upload-artifact@v2
        with:
          path: soracom/dist/ghactions/
